# Generated by Django 5.1.1 on 2024-10-10 19:11

from django.db import migrations
from entries.models import Task
from pathlib import Path

import csv


def load_csv_data(apps, schema_editor):
    base_dir = Path(__file__).resolve().parent.parent
    file_path = base_dir / "data" / "mock_tasks.csv"

    with open(file_path, "r") as file:
        reader = csv.DictReader(file)
        for row in reader:
            Task.objects.create(**row)


def unload_csv_data(apps, schema_editor):
    base_dir = Path(__file__).resolve().parent.parent
    file_path = base_dir / "data" / "mock_tasks.csv"

    with open(file_path, "r") as file:
        reader = csv.DictReader(file)
        for row in reader:
            id = row["id"]
            task = Task.objects.get(id=id)
            task.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("entries", "0002_alter_task_options_alter_task_priority"),
    ]

    operations = [
        migrations.RunPython(load_csv_data, reverse_code=unload_csv_data),
    ]
