name: Deploy Django App to Azure

on:
    push:
        branches:
            - main
            - add-github-actions
    pull_request:
        branches:
            - main
            - add-github-actions

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Login to Azure
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Build and push Docker image
              run: |
                    docker build . -t Dockerfile -t internship.azurecr.io/taskapp:${{ github.sha }}

                    docker login internship.azurecr.io -u internship -p ${{ secrets.ACR_PASSWORD }}
                    docker push internship.azurecr.io/taskapp:${{ github.sha }}

            - name: Deploy to Azure Container App
              uses: azure/container-app-deploy@v1
              with:
                acrName: internship
                containerAppName: andrei
                resourceGroup: internship
                imageToDeploy: internship.azurecr.io/taskapp:${{ github.sha }}
